# Generated by Django 6.0.3 on 2026-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_debenture_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debenturecadastro',
            name='tipo_amortizacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
