# Generated by Django 6.0.3 on 2026-03-18 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_tipo_amortizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebentureFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_evento', models.DateField()),
                ('evento', models.CharField(max_length=60)),
                ('dt_pagamento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('taxa_percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('liquidacao', models.CharField(blank=True, max_length=100)),
                ('cod_deb', models.ForeignKey(db_column='cod_deb', on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='core.debenturecadastro')),
            ],
            options={
                'db_table': 'DebentureFluxo',
                'ordering': ['dt_evento', 'evento'],
                'unique_together': {('cod_deb', 'dt_evento', 'evento')},
            },
        ),
    ]
